esphome:
  name: tuya-ble-example

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: WARN
    
external_components:
  - source: components

esp32_ble_tracker:

tuya_ble_tracker:

tuya_ble_client:
  - id: tuya_client

tuya_ble_node:
  - mac_address: !secret mac_address
    local_key: !secret local_key
    tuya_ble_client_id: tuya_client
